<?php

namespace SupinfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampusRepository extends EntityRepository
{
}
