<?php

namespace SupinfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param Campus $campus
     * @return array
     */
    public function getNewsForCampus(Campus $campus)
    {
        $query = $this->createQueryBuilder("p");
        $query->select("partial p.{id,title,content}")
            ->addSelect("partial u.{id,lastname, username}")
            ->from("SupinfoBundle:Post","post")
            ->join("p.createdBy","u","u.id=p.createdBy")
            ->where("p.campus = :campus")
            ->orWhere("p.campus is null")
            ->setParameter("campus", $campus)
        ;
        $res = $query->getQuery()->getScalarResult();
        return $res;
    }
}
